spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/netview"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  servlet:
    session:
      timeout: 90m
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 7070