spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  servlet:
    session:
      timeout: 90m
